schema_version = "1.0.0"
id = "blendup"
version = "0.6.1"
name = "BlendUp"
tagline = "Manage 3D assets and export to Godot or Unity"
maintainer = "BlendUp"
type = "add-on"
tags = ["Import-Export", "Pipeline"]
blender_version_min = "4.2.0"
license = ["SPDX:MIT"]
